app/home/forms.py
from email import message

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, ValidationError, EqualTo, Email, Regexp

from app.models import User

"""

"""


class LoginForm(FlaskForm):
    name = StringField(label="账号",
                       validators=[DataRequired("账号不能为空")],
                       description="账号",
                       render_kw={
                           "class": "form-control",
                           "placeholder": "请输入账号",
                       })
    pwd = PasswordField(label="密码",
                        validators=[DataRequired("密码不能为空")],
                        description="密码",
                        render_kw={
                            "class": "form-control",
                            "placeholder": "请输入密码",
                        }
                        )
    submit = SubmitField("登录",
                         render_kw={
                             "class": "btn btn-lg btn-success",

                         })







# class RegisterForm(FlaskForm):
#     name = StringField(label="昵称",
#                        validators=[DataRequired("麻烦请输入昵称信息")],
#                        description="昵称",
#                        render_kw={
#                            "class": "form-control input-lg",
#                            "placeholder": "请输入昵称",
#                        }
#                        )
#     email = StringField(label="邮箱",
#                         validators=[
#                             DataRequired("麻烦请输入邮箱信息"),
#                             Email("邮箱格式不正确！")
#                         ],
#                         description="邮箱",
#                         render_kw={
#                             "class": "form-control input-lg",
#                             "placeholder": "请输入邮箱",
#                         }
#                         )
#     phone = StringField(label="手机",
#                         validators=[
#                             DataRequired("麻烦请输入手机号码信息"),
#                             Regexp("1[3458]\\d{9}", message="手机格式不正确")
#                         ],
#                         description="手机",
#                         render_kw={
#                             "class": "form-control input-lg",
#                             "placeholder": "请输入手机号码",
#                         }
#                         )
#     pwd = PasswordField(label="密码",
#                         validators=[
#                             DataRequired("请输入密码信息"),
#
#                         ],
#                         description="密码",
#                         render_kw={
#                             "class": "form-control",
#                             "placeholder": "请输入密码",
#                         }
#                         )
#     repwd = PasswordField(label="确认密码",
#                           validators=[
#                               DataRequired("请输入确认密码信息"),
#                               EqualTo('pwd', message="两次密码输入不一致！")
#                           ],
#                           description="密码",
#                           render_kw={
#                               "class": "form-control",
#                               "placeholder": "请输入确认密码",
#                           }
#                           )
#     submit = SubmitField(
#         "注册",
#         render_kw={
#             "class": "btn btn-lg btn-success",
#         }
#     )
#
#     def validate_name(self, field):
#         name = field.data
#         user = User.query.filter_by(name=name).count()
#         if user == 1:
#             raise ValidationError("昵称已经存在!")
#
#     def validate_email(self, field):
#         email = field.data
#         user = User.query.filter_by(email=email).count()
#         if user == 1:
#             raise ValidationError("邮箱已经存在!")
#
#     def validate_phone(self, field):
#         phone = field.data
#         user = User.query.filter_by(phone=phone).count()
#         if user == 1:
#             raise ValidationError("手机已经存在!")
"""

用户名:name
邮箱:email
手机:phone
密码:pwd
确认密码:repwd
"""


class RegisterForm(FlaskForm):
    name = StringField(label="用户名",
                       validators=[DataRequired("请输入非空用户名")],
                       description="帐户",
                       render_kw={
                           "class": "form-control",
                           "placeholder": "请输入用户名"}
                       )
    email = StringField(label="邮箱",
                        validators=[DataRequired("请输入非空邮箱"),
                                    Email("请输入正确email格式")],
                        description="邮箱",
                        render_kw={
                            "class":"form-control",
                            "placeholder":"请输入邮箱"
                        })
    phone = StringField(label="手机号",
                        validators=[DataRequired("请输入非空手机号"),
                                    Regexp("1[356789]\\d{9}",message="手机格式不正确")],
                        description="手机号",
                        render_kw={
                            "class":"form-control",
                            "placeholder": "请输入手机号"
                        })

    pwd = PasswordField(label="密码",
                        validators=[DataRequired("密码不能为空")],
                        description="密码",
                        render_kw={
                            "class":"form-control",
                            "placeholder": "请输入密码"
                        })
    repwd = PasswordField(label="确认密码",
                        validators=[DataRequired("确认密码不能为空"),
                                    EqualTo("pwd", "两次密码输入不一致")],
                        description="确认密码",
                        render_kw={
                            "class": "form-control",
                            "placeholder": "请再次输入密码"
                        })
    submit = SubmitField("注册",
                         render_kw={
                             "class":"btn btn-lg btn-success"
                         })

    def validate_name(self,field):
        name = field.data
        user_count = User.query.filter_by(name=name).count()
        if user_count == 1:
            raise ValidationError("该昵称已存在!!")

    def validate_email(self,field):
        email = field.data
        user_count = User.query.filter_by(email=email).count()
        if user_count == 1:
            raise ValidationError("该邮箱已存在!")

    def validate_phone(self,field):
        phone = field.data
        user_count = User.query.filter_by(phone=phone).count()
        if user_count == 1:
            raise ValidationError("该手机号已注册!")

app/home/__init__.py
from flask import Blueprint

home = Blueprint("home", __name__)

import app.home.views

app/home/views.py
from functools import wraps

from flask import Response, render_template, url_for, redirect, flash, session, request

from werkzeug.security import generate_password_hash

from . import home


def check_user_login(func):
  @wraps(func)
  def decorated_function(*args, **kwargs):
    if "user" not in session:
      return redirect(url_for("home.home_login", next=request.url))
    return func(*args, **kwargs)
  return decorated_function


@home.route("/test/")
@check_user_login
def mtest():
  return Response("this is the function.")


@home.route("/index/")
def home_index():
  return render_template("home/index.html")


@home.route('/')
def index():
    login_flag = 0
    user_name = ''
    if session.get('user'):
        login_flag = 1
        user_name = session['user']
    return render_template("home/index.html", login_flag=login_flag, username=user_name)


@home.route('/login_test/')
def home_login_test():
    from app.models import UserInfo
    user_list = UserInfo.query.all()
    return render_template("home/login_test.html", user_list=user_list)


@home.route("/add_user/<string:username>/<string:email>/<string:address>/")
def home_add_user(username, email, address):
    # 传入Model层， 存储数据库
    from app import db
    from app.models import UserInfo
    user = UserInfo(username=username, email=email, address=address)
    db.session.add(user)
    db.session.commit()
    print('save ok.')
    import json
    data = {'username': username, 'email': email, 'address': address}
    result = {'code': 200, 'message': 'ok', 'data': data}
    return Response(json.dumps(result))


@home.route("/add_category/<string:name>/")
def add_category(name):
    from app import db
    from app.models import Category
    cate = Category(name=name)
    db.session.add(cate)
    db.session.commit()
    import json
    data = {'name': 'name'}
    result = {"state": 200, "msg": 'ok', "data": data}
    return Response(json.dumps(result))


@home.route("/login/", methods=['POST','GET'])
def home_login():
    from app.home.forms import LoginForm
    from app import db
    from app.models import User
    form = LoginForm()
    print('11111111')
    if form.validate_on_submit():
        print('2222222')
        data = form.data
        user = User.query.filter_by(name=data["name"]).first()
        if user:
            if not user.check_pwd(data["pwd"]):
                flash("密码验证错误", "err")
                return redirect(url_for("home.home_login"))
        else:
            flash("用户不存在", "err")
            return redirect(url_for("home.home_login"))
        session["user"] = user.name
        session["user_id"] = user.uid


        return redirect(url_for("home.index"))

    return render_template('home/login.html',title="会员登录", form=form)


@home.route("/vip_login/")
def login():
    return render_template("home/vip_login.html")


@home.route("/wflogin/")
def home_wflogin():
    from .forms import LoginForm
    form_login = LoginForm()
    return render_template("home/wflogin.html", form_login=form_login)


@home.route("/logout/")
def home_logout():
    session.pop("name", None)
    session.pop("uid", None)
    return redirect(url_for("home.home_login"))


@home.route("/register/", methods=[ 'GET','POST'])
def home_register():
    from app import db
    from app.home.forms import RegisterForm
    from app.models import User
    form = RegisterForm()
    if form.validate_on_submit():
        data = form.data
        user = User(name=data["name"],email=data["email"],phone=data["phone"],pwd=generate_password_hash(data["pwd"]))
        db.session.add(user)
        db.session.commit()
        flash("恭喜!注册成功", "ok")
    return render_template("home/register.html", form=form)


@home.route("/wf_register/")
def home_wf_register():
    from .forms import RegisterForm
    form = RegisterForm()
    return render_template("home/wf_register.html", form=form)


@home.route("/animation/")
def animation():
    return render_template("home/animation.html")


@home.route("/play/")
def play():
    return render_template("home/play.html")

app/templates/home/animation.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>热映电影轮播图</title>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='animat/css/style.css') }}">
</head>
<body>
<!--轮播图 开始 -->
<div class="main_banner">
   <div class="main_banner_wrap">
      <canvas id="myCanvas" width="150" height="150"></canvas>
      <div class="main_banner_box" id="m_box">
         <a href="javascript:void(0)" class="banner_btn js_pre">
            <span class="banner_btn_arrow"><i></i></span>
         </a>
         <a href="javascript:void(0)" class="banner_btn btn_next js_next">
            <span class="banner_btn_arrow"><i></i></span>
         </a>
         <ul>
            <li id="imgCard0">
               <a href=""><span style="opacity:0;"></span></a>
               <img src="{{ url_for('static', filename='animat/main_banner/big0020150102211033.jpg') }}" alt="">
               <p style="bottom:0">周杰伦粉丝版MV</p>
            </li>
            <li id="imgCard1">
               <a href=""><span style="opacity:0.4;"></span></a>
               <img src="{{ url_for('static', filename='animat/main_banner/big0120150101183428.jpg') }}" alt="">
               <p>乐侃有声节目第二期</p>
            </li>
            <li id="imgCard2">
               <a href=""><span style="opacity:0.4;" ></span></a>
               <img src="{{ url_for('static', filename='animat/main_banner/big0320150101183351.jpg') }}" alt="">
               <p>乐见大牌：”荣“耀之声，”维“我独尊</p>
            </li>
            <li id="imgCard3">
               <a href=""><span style="opacity:0.4;"></span></a>
               <img src="{{ url_for('static', filename='animat/main_banner/big0420150101224343.jpg') }}" alt="">
               <p>王力宏四年心血结晶</p>
            </li>
            <li id="imgCard4">
               <a href=""><span style="opacity:0.4;"></span></a>
               <img src="{{ url_for('static', filename='animat/main_banner/big0720150102210934.jpg') }}" alt="">
               <p>MV精选：《武媚》女神团美艳大比拼</p>
            </li>
         </ul>
         <!--火狐倒影图层-->
         <p id="rflt"></p>
         <!--火狐倒影图层-->
      </div>
      <!--序列号按钮-->
      <div class="btn_list">
         <span class="curr"></span><span></span><span></span><span></span><span></span>
      </div>
   </div>

</div>
<!--轮播图 结束 -->

<script type="text/javascript" src="{{ url_for('static', filename='animat/js/jquery.js') }}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='animat/js/script.js') }}"></script>

</body>
</html>

app/templates/home/home.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',  filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }

    </style>
    <style>
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="index.html" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',  filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="search.html"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.home_index')}}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.home_login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.home_register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.home_logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="user.html"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->
<div class="container" style="margin-top:76px">
    {% block content %}
    {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;1000phone.com by  zhouguangyou&nbsp;2018.
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',  filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',  filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',  filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',  filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',  filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>
</body>
</html>

app/templates/home/index.html
{% extends "home/layout.html" %}
{% block li %}
     {% if login_flag == 1 %}
         <a>
            欢迎您，<span style="color: red"> {{ username }} </span>
         </a>
     {% else %}
        <li>
            <a class="curlink" href="{{ url_for('home.home_login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
        </li>
        <li>
            <a class="curlink" href="{{ url_for('home.home_register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
        </li>
     {% endif %}
 {% endblock %}

{% block content %}
    <!--热门电影-->
<section id="hotmovie" style="margin-top:76px">
    <div class="container">
        <div class="row wow fadeInRight" data-wow-delay="0.6s">
            <div class="row">
                <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no src="{{ url_for('home.animation') }}"></iframe>
            </div>
        </div>
    </div>
</section>
<!--热门电影-->
<!--电影列表-->
<section id="movielist">
    <div class="container">
        <div class="row wow fadeIn" data-wow-delay="0.6s">
            <div class="col-md-12 table-responsive">
                <table class="table text-left table-bordered" id="movietags">
                    <tr>
                        <td style="width:10%;">电影标签</td>
                        <td style="width:90%;">
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                            &nbsp;
                            <a class="label label-info"><span class="glyphicon glyphicon-tag"></span>&nbsp;标签一</a>
                    </tr>
                    <tr>
                        <td>电影星级</td>
                        <td>
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;一星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;二星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;三星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;四星</a>
                            &nbsp;
                            <a class="label label-warning"><span class="glyphicon glyphicon-star"></span>&nbsp;五星</a>
                        </td>
                    </tr>
                    <tr>
                        <td>上映时间</td>
                        <td>
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;最近</a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2017</a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2016</a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;2015</a>
                            &nbsp;
                            <a class="label label-default"><span class="glyphicon glyphicon-time"></span>&nbsp;更早</a>
                        </td>
                    </tr>
                    <tr>
                        <td>播放数量</td>
                        <td>
                            <a class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</a>
                            &nbsp;
                            <a class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</a>
                        </td>
                    </tr>
                    <tr>
                        <td>评论数量</td>
                        <td>
                            <a class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</a>
                            &nbsp;
                            <a class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</a>
                        </td>
                    </tr>
                </table>
            </div>
            <!--
            通过jinja2模板语法提供的for语句循环展示影片内容信息。
            -->
            {% for v in range(1, 13) %}
            <div class="col-md-3">
                <div class="movielist text-center">
                    <!--<img data-original="holder.js/262x166"
                             class="img-responsive lazy center-block" alt="">-->
                    <img src="holder.js/262x166" class="img-responsive center-block" alt="">
                    <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                        <span style="color:#999;font-style: italic;">环太平洋</span><br>
                        <div>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                            <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                        </div>
                    </div>
                    <a href="/home/play/" class="btn btn-primary" target="_blank" role="button"><span class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                </div>
            </div>
            {% endfor %}

            <div class="col-md-12">
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        <li>
                            <a href="#" aria-label="First">
                                <span aria-hidden="true">首页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Previous">
                                <span aria-hidden="true">上一页</span>
                            </a>
                        </li>
                        <li><a href="#">1&nbsp;/&nbsp;10</a></li>
                        <li>
                            <a href="#" aria-label="Next">
                                <span aria-hidden="true">下一页</span>
                            </a>
                        </li>
                        <li>
                            <a href="#" aria-label="Last">
                                <span aria-hidden="true">尾页</span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>
<!--电影列表-->

{% endblock %}

app/templates/home/layout.html
<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>微电影</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='base/images/logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static',  filename='base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/bootstrap-movie.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }

    </style>
    <style>
        .media{
            padding:3px;
            border:1px solid #ccc
        }

    </style>
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="index.html" class="navbar-brand" style="width:250px;">
                <img src="{{ url_for('static',  filename='base/images/logo.png') }}" style="height:30px;">&nbsp;微电影
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入电影名！">
                    <span class="input-group-btn">
                        <a class="btn btn-default" href="search.html"><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.home_login') }}"><span class="glyphicon glyphicon-film"></span>&nbsp;电影</a>
                </li>
                <li>
                    {% block li %}

                    {% endblock %}
                </li>

                <!--<li>
                    <a class="curlink" href="{{ url_for('home.home_login')}}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.home_register')}}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>-->
                <li>
                    <a class="curlink" href="{{ url_for('home.home_logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="user.html"><span class="glyphicon glyphicon-user"></span>&nbsp;会员</a>
                </li>
            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->

    {% block content %}

    {% endblock %}

<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;1000phone.com by  zhouguangyou&nbsp;2018.
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',  filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',  filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',  filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ url_for('static',  filename='base/js/wow.min.js') }}"></script>
<script src="{{ url_for('static',  filename='lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
    });

</script>
</body>
</html>

app/templates/home/login_test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form>
    {% for user in user_list %}
        <h3>{{ user.username,user.email,user.address }}</h3>

    {% endfor %}

</form>

</body>
</html>

app/templates/home/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/home/wflogin.html
{% extends "home/home.html" %}

{% block content %}

    <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <span class="glyphicon glyphicon-log-in"></span>
                </h3>
            </div>
            <div class="panel-body">
                <form>
                    <fieldset>
                        <div class="form-group">
                            <label for="input_contact">
                                <span class="glyphicon glyphicon-user"></span>账号
                            </label>
                            {{ form_login.name }}
                        </div>
                        <div class="form-group">
                            <label for="input_password">
                                <span class="glyphicon glyphicon-lock"></span>密码
                            </label>
                            {{ form_login.pwd }}
                        </div>
                        {{ form_login.submit }}

                    </fieldset>
                </form>
            </div>


        </div>

    </div>

{% endblock %}